package com.example.demo.Controllers;


import com.example.demo.domain.Customer;
import com.example.demo.domain.CustomerRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;


//@RestController
//public class APIController{
//    @GetMapping(value = {"/","/index"})
//    public String Home(){
//        return "Xin vhào các bạn mình là tèo";
//    }
//}

@RestController
public class APIController {

    @Autowired // This means to get the bean called customerRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private CustomerRepository customerRepository;

    @GetMapping(value = "/")
    public String Home(){
        return "hello";
    }

    @GetMapping(value="/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewUser (@RequestParam String name) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Customer c = new Customer();
        c.setName(name);

        customerRepository.save(c);
        return "Saved";
    }

    @GetMapping(value={"/all"})
    public @ResponseBody Iterable<Customer> getAllUsers() {
        // This returns a JSON or XML with the users
        return customerRepository.findAll();
    }
}

